// * HTTP Status Codes for different error types
const ErrorStatusCode = {
  // ? 400 - Bad Request
  VALIDATION_FAILED: 400,
  INSUFFICIENT_STOCK: 400,
  INVALID_ORDER_STATUS: 400,
  CANNOT_DELETE_USER_WITH_ORDERS: 400,
  ONLY_PENDING_ORDERS_CAN_BE_DELETED: 400,
  CURRENT_PASSWORD_REQUIRED: 400,
  CURRENT_PASSWORD_INCORRECT: 400,

  // ? 401 - Unauthorized
  INVALID_CREDENTIALS: 401,
  TOKEN_REQUIRED: 401,
  TOKEN_INVALID_OR_EXPIRED: 401,
  REFRESH_TOKEN_REQUIRED: 401,

  // ? 403 - Forbidden
  CANNOT_CHANGE_OWN_ROLE: 403,
  CANNOT_DELETE_OWN_ACCOUNT: 403,
  INSUFFICIENT_PERMISSIONS: 403,

  // ? 404 - Not Found
  RESOURCE_NOT_FOUND: 404,
  USER_NOT_FOUND: 404,
  PRODUCT_NOT_FOUND: 404,
  CATEGORY_NOT_FOUND: 404,
  ORDER_NOT_FOUND: 404,

  // ? 409 - Conflict
  USER_ALREADY_EXISTS: 409,
  RESOURCE_ALREADY_EXISTS: 409,
  CATEGORY_NAME_EXISTS: 409,
  EMAIL_ALREADY_EXISTS: 409,
  CANNOT_DELETE_CATEGORY_WITH_PRODUCTS: 409,

  // ? 503 - Service Unavailable
  DB_UNAVAILABLE: 503,
  SERVICE_UNAVAILABLE: 503,
};

module.exports = {
  ErrorStatusCode,
};
